name: preview_on_pr_update

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  preview:
    # only run when updating an 'Open' PR
    if: github.event.pull_request.state == 'open'
    uses: jalantechnologies/github-ci/.github/workflows/ci.yml@ankit/feat/aws_deploy_support
    concurrency:
      group: ci-preview-${{ github.event.pull_request.head.ref }}
      cancel-in-progress: true
    with:
      analyze_base: main
      app_name: boilerplate-mern
      app_env: preview
      app_hostname: '{1}.preview.platform.jalantechnologies.com'
      branch: ${{ github.event.pull_request.head.ref }}
      build_args: |
        NODE_CONFIG_ENV=preview
      checks: "['npm:lint', 'compose:test', 'compose:e2e']"
      pull_request_number: ${{ github.event.number }}
      sonar_host_url: ${{ vars.SONAR_HOST_URL }}
      aws_cluster_name: ${{ vars.AWS_CLUSTER_NAME }}
      aws_region: ${{ vars.AWS_REGION }}
      aws_use_ecr: true
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}
